name: chat_app_clone
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.6.1







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  pinput: ^5.0.1
  image_picker: ^1.1.2
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
